// Run: node seed-topics.cjs
const https = require("https");

const SUPABASE_URL = "https://pzwqbzfhdgtdpqhvnlzc.supabase.co";
const SUPABASE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6d3FiemZoZGd0ZHBxaHZubHpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyNjI1ODQsImV4cCI6MjA5NDgzODU4NH0.Phv9sTrVRGcZ7VUrc_lgvRxGPajofclFxK9kKaN02y0";

const TOPICS = [
  { id: 1, title: "Family", questions: [{ text: "What family members do you live with?", translation: "Bạn đang sống cùng với những thành viên nào trong gia đình?", sample_answer: "I live with my parents and my younger sister." }, { text: "What family members are you close to?", translation: "Bạn thân thiết, gần gũi với thành viên nào nhất?", sample_answer: "I am closest to my mother because she always listens to me." }, { text: "Do you have any siblings?", translation: "Bạn có anh chị em ruột nào không?", sample_answer: "Yes, I have one sister who is very funny." }] },
  { id: 2, title: "Friends", questions: [{ text: "Who is your best friend?", translation: "Ai là người bạn thân nhất của bạn?", sample_answer: "My best friend is Nam, we play football together." }, { text: "What do you and your friends do together?", translation: "Bạn và các bạn của mình thường làm gì cùng nhau?", sample_answer: "We usually play computer games and do homework on weekends." }, { text: "What's your favourite memory you've shared with a friend?", translation: "Kỷ niệm yêu thích nhất mà bạn từng có với bạn thân là gì?", sample_answer: "My favorite memory was when we built a paper treehouse last summer." }] },
  { id: 3, title: "Holidays", questions: [{ text: "Where is your favourite place to go on holiday?", translation: "Địa điểm du lịch yêu thích nhất của bạn là ở đâu?", sample_answer: "My favorite holiday place is Nha Trang beach." }, { text: "If you could go anywhere in the world for a holiday, where would you go?", translation: "Nếu có thể đi du lịch bất cứ nơi nào trên thế giới, bạn sẽ đi đâu?", sample_answer: "If I could travel anywhere, I would visit Tokyo to see cherry blossoms." }, { text: "What is your favourite holiday experience?", translation: "Trải nghiệm kỳ nghỉ thú vị nhất của bạn là gì?", sample_answer: "My best holiday experience was learning to swim in the deep ocean." }] },
  { id: 4, title: "Games", questions: [{ text: "What are your favourite games to play at home?", translation: "Những trò chơi yêu thích bạn hay chơi ở nhà là gì?", sample_answer: "At home, I love playing chess with my father." }, { text: "Do you prefer video games or board games?", translation: "Bạn thích trò chơi điện tử hay cờ bàn hơn?", sample_answer: "I prefer board games because they help connect family members." }, { text: "Do you think playing games are good for you? Why?", translation: "Bạn có nghĩ chơi trò chơi là tốt cho bản thân không? Tại sao?", sample_answer: "Yes, because playing games helps train our brains and reduces stress." }] },
  { id: 5, title: "Shopping", questions: [{ text: "What is your favourite thing to buy?", translation: "Thứ yêu thích nhất mà bạn hay mua sắm là gì?", sample_answer: "My favorite things to buy are comic books and science models." }, { text: "How often do you go shopping?", translation: "Bạn có thường xuyên đi mua sắm không?", sample_answer: "I only go shopping once a month with my parents." }, { text: "Do you like/dislike shopping? Why?", translation: "Bạn thích hay ghét việc mua sắm? Tại sao?", sample_answer: "I like shopping because looking at new toys is very exciting." }] },
  { id: 6, title: "Home Town", questions: [{ text: "What's your area like?", translation: "Khu vực bạn sống trông như thế nào?", sample_answer: "My area is very green, peaceful and friendly." }, { text: "Do you like where you live? Why?", translation: "Bạn có thích nơi mình đang sống không? Tại sao?", sample_answer: "I love living here because I have many kind neighbors." }, { text: "What's the best/worst thing about where you live?", translation: "Điều tốt nhất hoặc tồi tệ nhất về nơi bạn sống là gì?", sample_answer: "The best thing is the beautiful park nearby, but the traffic can be noisy." }] },
  { id: 7, title: "Future", questions: [{ text: "Where do you see yourself in ten years?", translation: "Bạn thấy bản thân mình ở đâu trong 10 năm nữa?", sample_answer: "In ten years, I see myself as a software developer." }, { text: "What do you think will change in the next 100 years?", translation: "Bạn nghĩ điều gì sẽ thay đổi trong vòng 100 năm tới?", sample_answer: "In 100 years, I believe we will have flying cars and robot assistants." }, { text: "What do you most want to achieve in your life?", translation: "Bạn mong muốn đạt được thành tựu lớn nhất nào trong đời?", sample_answer: "I want to build a school for kids who are in difficult situations." }] },
  { id: 8, title: "School", questions: [{ text: "What's your favourite subject? Why?", translation: "Môn học yêu thích nhất của bạn là gì? Tại sao?", sample_answer: "My favorite subject is English because it helps me talk to foreigners." }, { text: "What's your least favourite subject? Why?", translation: "Môn học bạn ít thích nhất là gì? Tại sao?", sample_answer: "My least favorite is history because there are too many dates to memorize." }, { text: "What's the best thing about going to school?", translation: "Điều tuyệt vời nhất của việc đi học là gì?", sample_answer: "The best part is playing with my classmates during break time." }] },
  { id: 9, title: "Jobs", questions: [{ text: "What do you think the best job is? Why?", translation: "Bạn nghĩ công việc tốt nhất thế giới là gì? Tại sao?", sample_answer: "I think being a doctor is the best job because they can save lives." }, { text: "What jobs do your family members have?", translation: "Các thành viên trong gia đình bạn làm những nghề gì?", sample_answer: "My father is an engineer and my mother is a teacher." }, { text: "What job do you think you'll have when you're older?", translation: "Bạn nghĩ mình sẽ làm nghề gì khi lớn lên?", sample_answer: "I think I will become a designer because I love drawing." }] },
  { id: 10, title: "Food", questions: [{ text: "What's your favourite food?", translation: "Món ăn yêu thích nhất của bạn là gì?", sample_answer: "My favorite food is traditional Vietnamese Pho." }, { text: "What's your least favourite food?", translation: "Món ăn bạn ghét nhất hoặc ít thích nhất là gì?", sample_answer: "I dislike seafood or anything that has a strong fishy smell." }, { text: "What would you choose as your last meal?", translation: "Bạn sẽ chọn món gì nếu đó là bữa ăn cuối cùng?", sample_answer: "I would choose a giant cheese pizza and fresh strawberry juice." }] },
  { id: 11, title: "Environment", questions: [{ text: "What's bad for the environment?", translation: "Điều gì gây hại lớn cho môi trường?", sample_answer: "Plastic bags and smoking factories are bad for the environment." }, { text: "What can we do to help improve our environment?", translation: "Chúng ta có thể làm gì để cải thiện môi trường sống xung quanh?", sample_answer: "We can plant more trees and start recycling plastic bottles." }, { text: "Why do people care about the environment?", translation: "Tại sao con người ngày càng quan tâm đến bảo vệ môi trường?", sample_answer: "People care because we need a clean planet to stay healthy and survive." }] },
  { id: 12, title: "Health", questions: [{ text: "Have you ever been ill? How did it feel?", translation: "Bạn đã từng bị ốm chưa? Khi đó bạn cảm thấy thế nào?", sample_answer: "Yes, I had a high fever last winter and felt extremely cold and weak." }, { text: "What things can we do to stay healthy?", translation: "Chúng ta nên làm những gì để luôn giữ cơ thể khỏe mạnh?", sample_answer: "We should do exercise every morning and eat more vegetables." }, { text: "What happens when you're ill?", translation: "Điều gì xảy ra với cơ thể khi bạn bị ốm?", sample_answer: "When you are ill, you feel tired and must stay in bed." }] },
  { id: 13, title: "Restaurants", questions: [{ text: "What's your favourite restaurant?", translation: "Nhà hàng yêu thích nhất của bạn là nhà hàng nào?", sample_answer: "My favorite restaurant is a local pizza store near my school." }, { text: "Describe a bad restaurant experience.", translation: "Hãy miêu tả một trải nghiệm tồi tệ tại một nhà hàng bạn từng ăn.", sample_answer: "Once, the soup was cold and it took an hour to serve the main dish." }, { text: "If you had your own restaurant, what would it be like?", translation: "Nếu tự mở một nhà hàng, bạn muốn nhà hàng đó sẽ trông như thế nào?", sample_answer: "My own restaurant would serve delicious sweet cakes and fruit shakes." }] },
  { id: 14, title: "Sports", questions: [{ text: "Do you enjoy playing sports? Why?", translation: "Bạn có thích chơi thể thao không? Tại sao?", sample_answer: "Yes, I do, because sports help me stay active and healthy." }, { text: "What's your favourite/least favourite sport?", translation: "Môn thể thao yêu thích nhất / ít thích nhất của bạn là gì?", sample_answer: "My favorite sport is badminton, and my least favorite is swimming." }, { text: "Do you enjoy watching sports? Why/why not?", translation: "Bạn có thích xem thể thao không? Tại sao có hoặc không?", sample_answer: "I enjoy watching football with my family on TV because it's exciting." }] },
  { id: 15, title: "Superpowers", questions: [{ text: "What superpower would you have?", translation: "Nếu được chọn, bạn muốn sở hữu siêu năng lực nào?", sample_answer: "I would choose the power to fly so I can travel around the world." }, { text: "What would the world be like with real superheroes?", translation: "Thế giới sẽ ra sao nếu có những siêu anh hùng ngoài đời thực?", sample_answer: "The world would be much safer because they can stop crimes." }, { text: "Would you rather be a superhero or a supervillain?", translation: "Bạn muốn làm một siêu anh hùng hay một kẻ siêu phản diện hơn?", sample_answer: "I would choose to be a superhero to save people in dangerous situations." }] },
  { id: 16, title: "Money", questions: [{ text: "If you had all the money in the world, what would you buy?", translation: "Nếu bạn có tất cả số tiền trên thế giới, bạn sẽ mua gì đầu tiên?", sample_answer: "I would buy a huge library and build schools for poor children." }, { text: "Is money important? Why?", translation: "Tiền bạc có quan trọng không? Tại sao?", sample_answer: "Yes, because it helps us pay for food, school fees and healthcare." }, { text: "Can money be a bad thing?", translation: "Tiền bạc có thể mang lại những mặt xấu hay tác hại gì không?", sample_answer: "Yes, it can make people greedy and start fights with each other." }] },
  { id: 17, title: "Would You Rather", questions: [{ text: "Would you rather be an astronaut or an actor?", translation: "Bạn muốn trở thành một phi hành gia hay một diễn viên hơn?", sample_answer: "I would rather be an astronaut to study distant planets." }, { text: "Would you rather learn to fly a plane or a rocket?", translation: "Bạn muốn học cách lái máy bay hay lái tên lửa vũ trụ?", sample_answer: "I would choose to fly a rocket because it travels extremely fast." }, { text: "Would you rather live under the sea or in space?", translation: "Bạn muốn sống dưới đáy biển sâu hay sống ngoài vũ trụ bao la hơn?", sample_answer: "I would prefer to live in space to see the stars up close." }] },
  { id: 18, title: "Gifts", questions: [{ text: "What's the best gift you've ever received?", translation: "Món quà tuyệt vời nhất bạn từng nhận được là gì?", sample_answer: "The best gift was a cool bicycle from my father on my birthday." }, { text: "What's the worst gift you've received?", translation: "Món quà tệ nhất hoặc không ưng ý nhất bạn từng nhận là gì?", sample_answer: "The worst gift was a notebook with a broken cover page." }, { text: "Do you enjoy giving gifts? Why?", translation: "Bạn có thích việc tặng quà cho người khác không? Tại sao?", sample_answer: "Yes, because seeing other people happy makes me feel wonderful." }] },
  { id: 19, title: "Weather", questions: [{ text: "Do you prefer warm or cold weather?", translation: "Bạn thích thời tiết ấm áp hay lạnh giá hơn?", sample_answer: "I prefer warm weather because I can play outside with friends." }, { text: "Do you like snow? Why?", translation: "Bạn có thích tuyết rơi không? Tại sao có hoặc không?", sample_answer: "Yes, because snow is beautiful and I can build a snowman." }, { text: "What's your favourite summer memory?", translation: "Kỷ niệm đẹp nhất của bạn vào một mùa hè là gì?", sample_answer: "My favorite memory is camping in the pine forest with my parents." }] },
  { id: 20, title: "Films", questions: [{ text: "What's your favourite film genre? Why?", translation: "Thể loại phim yêu thích nhất của bạn là gì? Tại sao?", sample_answer: "My favorite genre is sci-fi because of the space technology." }, { text: "What's your favourite film?", translation: "Bộ phim yêu thích nhất của bạn tên là gì?", sample_answer: "My favorite film is Harry Potter because of the magic world." }, { text: "Which film character would you like to be?", translation: "Nhân vật điện ảnh nào bạn muốn hóa thân thành nhất?", sample_answer: "I would like to be Ironman so I can fly in a high-tech suit." }] },
  { id: 21, title: "Books", questions: [{ text: "Do you enjoy reading? Why?", translation: "Bạn có thích đọc sách không? Tại sao?", sample_answer: "Yes, because reading brings me into fantasy adventure stories." }, { text: "What's your favourite type of book?", translation: "Thể loại sách yêu thích nhất của bạn là gì?", sample_answer: "My favorite books are detective and mystery comic series." }, { text: "Why is reading good for you?", translation: "Tại sao việc đọc sách lại mang lại nhiều lợi ích tốt cho bạn?", sample_answer: "It expands our vocabulary and teaches us many lessons." }] },
  { id: 22, title: "Celebrations", questions: [{ text: "Do you celebrate your birthday? How?", translation: "Bạn có kỷ niệm sinh nhật của mình không? Tổ chức như thế nào?", sample_answer: "Yes, I celebrate with a small party, delicious cake and songs." }, { text: "What is your favourite celebration?", translation: "Ngày lễ kỷ niệm/lễ hội yêu thích nhất của bạn là gì?", sample_answer: "My favorite celebration is the Mid-Autumn Festival because of the lanterns." }, { text: "If you could create a new holiday, what would it be?", translation: "Nếu có thể tự sáng tạo ra một ngày nghỉ lễ mới, bạn sẽ tạo ngày gì?", sample_answer: "It would be called 'Lazy Day' where no one has to do homework." }] },
  { id: 23, title: "Feelings", questions: [{ text: "When was the happiest you've ever been?", translation: "Khoảnh khắc hạnh phúc nhất từ trước đến nay của bạn là khi nào?", sample_answer: "The happiest was when I got a cute white puppy as a surprise." }, { text: "When was the angriest you've ever been?", translation: "Lần bạn cảm thấy tức giận nhất là khi nào?", sample_answer: "The angriest was when my brother accidentally broke my robot toy." }, { text: "What scares you the most?", translation: "Điều gì làm bạn cảm thấy sợ hãi nhất?", sample_answer: "Deep water and poisonous spiders are the things that scare me most." }] },
  { id: 24, title: "Aliens", questions: [{ text: "Do you think aliens exist?", translation: "Bạn có tin rằng người ngoài hành tinh thực sự tồn tại không?", sample_answer: "Yes, because the space universe is so vast and contains many stars." }, { text: "What would you do if aliens contacted you?", translation: "Bạn sẽ làm gì nếu một ngày người ngoài hành tinh liên lạc với bạn?", sample_answer: "I would say welcome and try to introduce my town to them." }, { text: "Would you rather live with aliens or stay on Earth?", translation: "Bạn muốn sống cùng người ngoài hành tinh hay ở lại Trái Đất hơn?", sample_answer: "I would definitely choose to stay on Earth with my family." }] },
  { id: 25, title: "Seasons", questions: [{ text: "What's the best season?", translation: "Mùa nào là mùa đẹp nhất trong năm?", sample_answer: "The best season is autumn because the weather is windy and cool." }, { text: "What's the worst season?", translation: "Mùa nào là mùa tệ nhất hoặc khó chịu nhất?", sample_answer: "The worst is summer because it is too hot to play outside." }, { text: "Describe the differences between the seasons.", translation: "Hãy miêu tả sự khác nhau cơ bản giữa các mùa.", sample_answer: "Spring has green leaves, summer is hot, autumn has yellow leaves, winter is cold." }] },
  { id: 26, title: "Hobbies", questions: [{ text: "What do you do in your spare time?", translation: "Bạn thường làm gì vào những lúc rảnh rỗi?", sample_answer: "In my spare time, I love playing the piano and drawing." }, { text: "What new hobby would you like to try?", translation: "Sở thích mới nào bạn muốn thử sức trong tương lai?", sample_answer: "I would like to try skateboarding in the future." }, { text: "What hobby did you stop doing?", translation: "Sở thích nào trước đây bạn đã dừng, không chơi nữa?", sample_answer: "I stopped collecting stickers last year because it was hard to find new ones." }] },
  { id: 27, title: "Television", questions: [{ text: "What's your favourite TV show?", translation: "Chương trình truyền hình yêu thích nhất của bạn là gì?", sample_answer: "My favorite TV show is a nature documentary series on National Geographic." }, { text: "What do you like about watching TV?", translation: "Bạn thích điểm nào nhất khi xem TV?", sample_answer: "Watching TV teaches me interesting facts about animals." }, { text: "Who is your favourite TV character?", translation: "Nhân vật truyền hình yêu thích nhất của bạn là ai?", sample_answer: "My favorite character is Tom the cat because he is funny." }] },
  { id: 28, title: "Desert Island", questions: [{ text: "Who would you live with on a desert island?", translation: "Bạn muốn sống cùng ai nếu bị kẹt trên đảo hoang?", sample_answer: "I would live with my father because he is good at building shelters." }, { text: "What three items would you bring?", translation: "3 vật dụng quan trọng nào bạn sẽ mang theo bên mình?", sample_answer: "I would bring a solid knife, a metal cooking pot, and a lighter." }, { text: "What would be the hardest thing there?", translation: "Điều gì sẽ là thử thách khó khăn nhất khi ở đó?", sample_answer: "The hardest thing would be not having clean water or the internet." }] },
  { id: 29, title: "Music", questions: [{ text: "What kind of music do you enjoy?", translation: "Thể loại âm nhạc nào bạn yêu thích nhất?", sample_answer: "I enjoy classical piano melodies and energetic pop songs." }, { text: "How does music make you feel?", translation: "Âm nhạc thường mang lại cho bạn những cảm xúc như thế nào?", sample_answer: "Music makes me feel relaxed and peaceful when I study." }, { text: "Who is your favourite singer or artist?", translation: "Ai là ca sĩ hoặc nghệ sĩ âm nhạc yêu thích của bạn?", sample_answer: "My favorite singer is Taylor Swift because her songs tell beautiful stories." }] },
  { id: 30, title: "Birthdays", questions: [{ text: "Do you enjoy celebrating birthdays? Why?", translation: "Bạn có thích tổ chức tiệc sinh nhật không? Tại sao?", sample_answer: "Yes, because I can meet my friends and eat delicious food." }, { text: "How did you spend your last birthday?", translation: "Bạn đã đón ngày sinh nhật vừa qua của mình như thế nào?", sample_answer: "Last birthday, we went to the cinema and ate fried chicken." }, { text: "How would you spend your dream birthday?", translation: "Bạn sẽ đón một ngày sinh nhật trong mơ như thế nào nếu được chọn?", sample_answer: "My dream birthday would be spent with family at Disneyland." }] },
  { id: 31, title: "Dreams", questions: [{ text: "What's the last dream you remember?", translation: "Giấc mơ gần đây nhất mà bạn còn nhớ là gì?", sample_answer: "The last dream I remember was flying over a candy city." }, { text: "What's the weirdest dream you've had?", translation: "Giấc mơ kỳ lạ, quái dị nhất bạn từng mơ thấy là gì?", sample_answer: "The weirdest dream was speaking to a giant green turtle." }, { text: "What's the best dream you've had?", translation: "Giấc mơ tuyệt vời, đẹp đẽ nhất của bạn là giấc mơ nào?", sample_answer: "My best dream was scoring the winning goal in the World Cup." }] },
  { id: 32, title: "Animals", questions: [{ text: "What's your favourite animal? Why?", translation: "Con vật yêu thích nhất của bạn là gì? Tại sao?", sample_answer: "My favorite animal is the dolphin because they are smart." }, { text: "If you could be any animal, what would you be?", translation: "Nếu có thể hóa thân thành một con vật, bạn muốn làm con gì?", sample_answer: "If I were an animal, I would be an eagle to fly high." }, { text: "Would you rather be an animal or a human?", translation: "Bạn muốn làm động vật hay con người hơn?", sample_answer: "I would choose to be a human to create technology and draw." }] },
  { id: 33, title: "The Supernatural", questions: [{ text: "Do you believe in ghosts? Why/why not?", translation: "Bạn có tin vào ma quỷ không? Tại sao có hoặc không?", sample_answer: "No, because there is no scientific proof of ghosts." }, { text: "Do you know any ghost stories?", translation: "Bạn có biết câu chuyện ma, kinh dị nào không?", sample_answer: "I know a few scary stories for camping trips." }, { text: "If you were a ghost, where would you haunt?", translation: "Nếu hóa thành một hồn ma, bạn sẽ chọn địa điểm nào để dạo chơi?", sample_answer: "I would haunt a fun library to read free books at night." }] },
  { id: 34, title: "Celebrities", questions: [{ text: "Who is your favourite celebrity? Why?", translation: "Ai là người nổi tiếng yêu thích nhất của bạn? Tại sao?", sample_answer: "My favorite celebrity is Elon Musk because he creates rockets." }, { text: "Are celebrities important? Why?", translation: "Những người nổi tiếng có thực sự quan trọng không? Tại sao?", sample_answer: "Yes, because they can inspire people to do good things." }, { text: "Would you like to be a celebrity?", translation: "Bản thân bạn có muốn trở thành một người nổi tiếng không?", sample_answer: "No, I prefer having my private life with family." }] },
  { id: 35, title: "Fears", questions: [{ text: "What are you most afraid of?", translation: "Nỗi sợ hãi lớn nhất của bạn là gì?", sample_answer: "I am most afraid of public speaking in front of many people." }, { text: "Describe a time you faced a fear.", translation: "Hãy miêu tả một lần bạn dũng cảm đối diện với nỗi sợ hãi đó.", sample_answer: "I faced it by presenting my science project to my school last month." }, { text: "Why do people have different fears?", translation: "Tại sao mỗi người lại có những nỗi sợ hãi hoàn toàn khác nhau?", sample_answer: "Fears are different because of our memories and unique experiences." }] },
];

const BONG_BE_TOPICS = [
  { id: 1, title: "Test 1", questions: [{ text: "What's this?", target: "jacket" }, { text: "Are you wearing a jacket?" }, { text: "What clothes do you wear at school?" }, { text: "What's this?", target: "mouse" }, { text: "Do you like mice?" }, { text: "What's your favourite animal?" }, { text: "What are these?", target: "eggs" }, { text: "Do you eat eggs?" }, { text: "What do you eat for lunch?" }, { text: "Now, Tuệ Minh, how old are you?" }, { text: "How many people are there in your family?" }, { text: "Where do you watch television?", target: "living room" }, { text: "OK. Thank you, Tuệ Minh. Goodbye." }] },
  { id: 2, title: "Test 2", questions: [{ text: "What's this?", target: "ruler" }, { text: "What do you do in the morning?" }, { text: "What colour is your/this ruler?" }, { text: "What are these?", target: "grapes" }, { text: "Do you eat grapes?" }, { text: "What's your favourite fruit?" }, { text: "What's this?", target: "baseball" }, { text: "Do you play baseball?" }, { text: "What sport do you like?" }, { text: "Now, Tuệ Minh, where do you live?" }, { text: "Do you live in a flat / an apartment or a house?" }, { text: "How many rooms are there in your flat / apartment?" }, { text: "OK. Thank you, Tuệ Minh. Goodbye." }] },
  { id: 3, title: "Test 3", questions: [{ text: "What's this?", target: "watermelon" }, { text: "Do you like watermelon?" }, { text: "What's your favourite fruit?" }, { text: "What are these?", target: "shoes" }, { text: "Are your shoes clean or dirty?" }, { text: "What colour are your shoes?" }, { text: "What's this?", target: "TV/television" }, { text: "Do you like watching television?" }, { text: "Where is the television in your house?" }, { text: "Now, Tuệ Minh, is your school big or small?" }, { text: "What's your friend's name?" }, { text: "What sport do you play at school?" }, { text: "OK. Thank you, Tuệ Minh. Goodbye." }] },
  { id: 4, title: "Test 4", questions: [{ text: "What's this?", target: "milk" }, { text: "Do you drink milk?" }, { text: "What do you eat for breakfast?" }, { text: "What's this?", target: "house" }, { text: "Where do you live?" }, { text: "Do you have a big bedroom?" }, { text: "What's this?", target: "piano" }, { text: "Can you play the piano?" }, { text: "What colour is this piano?", target: "white piano" }, { text: "Now, Tuệ Minh, how many people are there in your family?" }, { text: "Is your teacher a man or a woman?" }, { text: "Where do you go with your friends?" }, { text: "OK. Thank you, Tuệ Minh. Goodbye." }] },
  { id: 5, title: "Test 5", questions: [{ text: "What's this?", target: "jacket" }, { text: "Are you wearing a jacket?" }, { text: "What colour is your/this jacket?" }, { text: "What's this?", target: "fish" }, { text: "Do you like fish?" }, { text: "What's your favourite animal?" }, { text: "Do you like orange juice?" }, { text: "What do you drink at breakfast?" }, { text: "Now, Tuệ Minh, how old are you?" }, { text: "Do you learn English at school?" }, { text: "Is your school big or small?" }, { text: "OK. Thank you, Tuệ Minh. Goodbye." }] },
];

async function post(path, body) {
  return new Promise((resolve, reject) => {
    const data = JSON.stringify(body);
    const url = new URL(SUPABASE_URL + path);
    const req = https.request({
      hostname: url.hostname, path: url.pathname, method: "POST", port: 443,
      headers: { "Content-Type": "application/json", "apikey": SUPABASE_KEY, "Authorization": `Bearer ${SUPABASE_KEY}`, "Prefer": "return=representation" },
    }, (res) => {
      let body = "";
      res.on("data", d => body += d);
      res.on("end", () => {
        try { resolve({ status: res.statusCode, data: JSON.parse(body) }); }
        catch { resolve({ status: res.statusCode, data: body }); }
      });
    });
    req.on("error", reject);
    req.write(data);
    req.end();
  });
}

async function seed() {
  console.log("Seeding standard topics...");
  for (const topic of TOPICS) {
    const res = await post("/rest/v1/topics", { title: topic.title, order_index: topic.id, type: "standard" });
    if (res.status !== 201) { console.error("Failed to insert topic:", topic.title, res.data); continue; }
    const topicId = res.data[0].id;
    console.log(`  ✓ ${topic.title} (${topicId})`);

    for (let i = 0; i < topic.questions.length; i++) {
      const q = topic.questions[i];
      const qRes = await post("/rest/v1/questions", {
        topic_id: topicId, text: q.text, translation: q.translation || null,
        sample_answer: q.sample_answer || null, target: null, order_index: i,
      });
      if (qRes.status !== 201) console.error("    Failed to insert question:", q.text, qRes.data);
    }
  }

  console.log("\nSeeding bongbe topics...");
  for (const topic of BONG_BE_TOPICS) {
    const res = await post("/rest/v1/topics", { title: topic.title, order_index: topic.id, type: "bongbe" });
    if (res.status !== 201) { console.error("Failed to insert topic:", topic.title, res.data); continue; }
    const topicId = res.data[0].id;
    console.log(`  ✓ ${topic.title} (${topicId})`);

    for (let i = 0; i < topic.questions.length; i++) {
      const q = topic.questions[i];
      const qRes = await post("/rest/v1/questions", {
        topic_id: topicId, text: q.text, translation: null,
        sample_answer: null, target: q.target || null, order_index: i,
      });
      if (qRes.status !== 201) console.error("    Failed to insert question:", q.text, qRes.data);
    }
  }

  console.log("\nDone!");
}

seed().catch(console.error);
